/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FirmRouteImport } from './routes/firm'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as ReturnRouteImport } from './routes/return'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as DesignBusinessOwnerRouteImport } from './routes/design.business-owner'
import { Route as DesignReviewerRouteImport } from './routes/design.reviewer'
import { Route as DesignSeasonalStaffRouteImport } from './routes/design.seasonal-staff'
import { Route as FirmBillingRouteImport } from './routes/firm.billing'
import { Route as FirmSettingsRouteImport } from './routes/firm.settings'
import { Route as FirmStaffRouteImport } from './routes/firm.staff'
import { Route as ReturnSignRouteImport } from './routes/return.sign'
import { Route as ReturnsIndexRouteImport } from './routes/returns.index'
import { Route as ReturnsIdRouteImport } from './routes/returns.$id'
import { Route as ReturnsIdIndexRouteImport } from './routes/returns.$id.index'
import { Route as ReturnsIdDocumentsRouteImport } from './routes/returns.$id.documents'
import { Route as ReturnsIdMessagesRouteImport } from './routes/returns.$id.messages'
import { Route as ReturnsIdReviewRouteImport } from './routes/returns.$id.review'
import { Route as ReturnsIdTasksRouteImport } from './routes/returns.$id.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmRoute = FirmRouteImport.update({
  id: '/firm',
  path: '/firm',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignBusinessOwnerRoute = DesignBusinessOwnerRouteImport.update({
  id: '/design/business-owner',
  path: '/design/business-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignReviewerRoute = DesignReviewerRouteImport.update({
  id: '/design/reviewer',
  path: '/design/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSeasonalStaffRoute = DesignSeasonalStaffRouteImport.update({
  id: '/design/seasonal-staff',
  path: '/design/seasonal-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmBillingRoute = FirmBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => FirmRoute,
} as any)
const FirmSettingsRoute = FirmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FirmRoute,
} as any)
const FirmStaffRoute = FirmStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => FirmRoute,
} as any)
const ReturnSignRoute = ReturnSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => ReturnRoute,
} as any)
const ReturnsIndexRoute = ReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIdRoute = ReturnsIdRouteImport.update({
  id: '/returns/$id',
  path: '/returns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIdIndexRoute = ReturnsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReturnsIdRoute,
} as any)
const ReturnsIdDocumentsRoute = ReturnsIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ReturnsIdRoute,
} as any)
const ReturnsIdMessagesRoute = ReturnsIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ReturnsIdRoute,
} as any)
const ReturnsIdReviewRoute = ReturnsIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ReturnsIdRoute,
} as any)
const ReturnsIdTasksRoute = ReturnsIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ReturnsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/firm': typeof FirmRouteWithChildren
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/return': typeof ReturnRouteWithChildren
  '/tasks': typeof TasksRoute
  '/design/business-owner': typeof DesignBusinessOwnerRoute
  '/design/reviewer': typeof DesignReviewerRoute
  '/design/seasonal-staff': typeof DesignSeasonalStaffRoute
  '/firm/billing': typeof FirmBillingRoute
  '/firm/settings': typeof FirmSettingsRoute
  '/firm/staff': typeof FirmStaffRoute
  '/return/sign': typeof ReturnSignRoute
  '/returns/$id': typeof ReturnsIdRouteWithChildren
  '/returns/': typeof ReturnsIndexRoute
  '/returns/$id/documents': typeof ReturnsIdDocumentsRoute
  '/returns/$id/messages': typeof ReturnsIdMessagesRoute
  '/returns/$id/review': typeof ReturnsIdReviewRoute
  '/returns/$id/tasks': typeof ReturnsIdTasksRoute
  '/returns/$id/': typeof ReturnsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/firm': typeof FirmRouteWithChildren
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/return': typeof ReturnRouteWithChildren
  '/tasks': typeof TasksRoute
  '/design/business-owner': typeof DesignBusinessOwnerRoute
  '/design/reviewer': typeof DesignReviewerRoute
  '/design/seasonal-staff': typeof DesignSeasonalStaffRoute
  '/firm/billing': typeof FirmBillingRoute
  '/firm/settings': typeof FirmSettingsRoute
  '/firm/staff': typeof FirmStaffRoute
  '/return/sign': typeof ReturnSignRoute
  '/returns': typeof ReturnsIndexRoute
  '/returns/$id/documents': typeof ReturnsIdDocumentsRoute
  '/returns/$id/messages': typeof ReturnsIdMessagesRoute
  '/returns/$id/review': typeof ReturnsIdReviewRoute
  '/returns/$id/tasks': typeof ReturnsIdTasksRoute
  '/returns/$id': typeof ReturnsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/firm': typeof FirmRouteWithChildren
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/return': typeof ReturnRouteWithChildren
  '/tasks': typeof TasksRoute
  '/design/business-owner': typeof DesignBusinessOwnerRoute
  '/design/reviewer': typeof DesignReviewerRoute
  '/design/seasonal-staff': typeof DesignSeasonalStaffRoute
  '/firm/billing': typeof FirmBillingRoute
  '/firm/settings': typeof FirmSettingsRoute
  '/firm/staff': typeof FirmStaffRoute
  '/return/sign': typeof ReturnSignRoute
  '/returns/$id': typeof ReturnsIdRouteWithChildren
  '/returns/': typeof ReturnsIndexRoute
  '/returns/$id/documents': typeof ReturnsIdDocumentsRoute
  '/returns/$id/messages': typeof ReturnsIdMessagesRoute
  '/returns/$id/review': typeof ReturnsIdReviewRoute
  '/returns/$id/tasks': typeof ReturnsIdTasksRoute
  '/returns/$id/': typeof ReturnsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/documents'
    | '/firm'
    | '/inbox'
    | '/profile'
    | '/questionnaire'
    | '/return'
    | '/tasks'
    | '/design/business-owner'
    | '/design/reviewer'
    | '/design/seasonal-staff'
    | '/firm/billing'
    | '/firm/settings'
    | '/firm/staff'
    | '/return/sign'
    | '/returns/$id'
    | '/returns/'
    | '/returns/$id/documents'
    | '/returns/$id/messages'
    | '/returns/$id/review'
    | '/returns/$id/tasks'
    | '/returns/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/documents'
    | '/firm'
    | '/inbox'
    | '/profile'
    | '/questionnaire'
    | '/return'
    | '/tasks'
    | '/design/business-owner'
    | '/design/reviewer'
    | '/design/seasonal-staff'
    | '/firm/billing'
    | '/firm/settings'
    | '/firm/staff'
    | '/return/sign'
    | '/returns'
    | '/returns/$id/documents'
    | '/returns/$id/messages'
    | '/returns/$id/review'
    | '/returns/$id/tasks'
    | '/returns/$id'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/documents'
    | '/firm'
    | '/inbox'
    | '/profile'
    | '/questionnaire'
    | '/return'
    | '/tasks'
    | '/design/business-owner'
    | '/design/reviewer'
    | '/design/seasonal-staff'
    | '/firm/billing'
    | '/firm/settings'
    | '/firm/staff'
    | '/return/sign'
    | '/returns/$id'
    | '/returns/'
    | '/returns/$id/documents'
    | '/returns/$id/messages'
    | '/returns/$id/review'
    | '/returns/$id/tasks'
    | '/returns/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  DocumentsRoute: typeof DocumentsRoute
  FirmRoute: typeof FirmRouteWithChildren
  InboxRoute: typeof InboxRoute
  ProfileRoute: typeof ProfileRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  ReturnRoute: typeof ReturnRouteWithChildren
  TasksRoute: typeof TasksRoute
  DesignBusinessOwnerRoute: typeof DesignBusinessOwnerRoute
  DesignReviewerRoute: typeof DesignReviewerRoute
  DesignSeasonalStaffRoute: typeof DesignSeasonalStaffRoute
  ReturnsIdRoute: typeof ReturnsIdRouteWithChildren
  ReturnsIndexRoute: typeof ReturnsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firm': {
      id: '/firm'
      path: '/firm'
      fullPath: '/firm'
      preLoaderRoute: typeof FirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/business-owner': {
      id: '/design/business-owner'
      path: '/design/business-owner'
      fullPath: '/design/business-owner'
      preLoaderRoute: typeof DesignBusinessOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/reviewer': {
      id: '/design/reviewer'
      path: '/design/reviewer'
      fullPath: '/design/reviewer'
      preLoaderRoute: typeof DesignReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/seasonal-staff': {
      id: '/design/seasonal-staff'
      path: '/design/seasonal-staff'
      fullPath: '/design/seasonal-staff'
      preLoaderRoute: typeof DesignSeasonalStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firm/billing': {
      id: '/firm/billing'
      path: '/billing'
      fullPath: '/firm/billing'
      preLoaderRoute: typeof FirmBillingRouteImport
      parentRoute: typeof FirmRoute
    }
    '/firm/settings': {
      id: '/firm/settings'
      path: '/settings'
      fullPath: '/firm/settings'
      preLoaderRoute: typeof FirmSettingsRouteImport
      parentRoute: typeof FirmRoute
    }
    '/firm/staff': {
      id: '/firm/staff'
      path: '/staff'
      fullPath: '/firm/staff'
      preLoaderRoute: typeof FirmStaffRouteImport
      parentRoute: typeof FirmRoute
    }
    '/return/sign': {
      id: '/return/sign'
      path: '/sign'
      fullPath: '/return/sign'
      preLoaderRoute: typeof ReturnSignRouteImport
      parentRoute: typeof ReturnRoute
    }
    '/returns/': {
      id: '/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof ReturnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/$id': {
      id: '/returns/$id'
      path: '/returns/$id'
      fullPath: '/returns/$id'
      preLoaderRoute: typeof ReturnsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/$id/': {
      id: '/returns/$id/'
      path: '/'
      fullPath: '/returns/$id/'
      preLoaderRoute: typeof ReturnsIdIndexRouteImport
      parentRoute: typeof ReturnsIdRoute
    }
    '/returns/$id/documents': {
      id: '/returns/$id/documents'
      path: '/documents'
      fullPath: '/returns/$id/documents'
      preLoaderRoute: typeof ReturnsIdDocumentsRouteImport
      parentRoute: typeof ReturnsIdRoute
    }
    '/returns/$id/messages': {
      id: '/returns/$id/messages'
      path: '/messages'
      fullPath: '/returns/$id/messages'
      preLoaderRoute: typeof ReturnsIdMessagesRouteImport
      parentRoute: typeof ReturnsIdRoute
    }
    '/returns/$id/review': {
      id: '/returns/$id/review'
      path: '/review'
      fullPath: '/returns/$id/review'
      preLoaderRoute: typeof ReturnsIdReviewRouteImport
      parentRoute: typeof ReturnsIdRoute
    }
    '/returns/$id/tasks': {
      id: '/returns/$id/tasks'
      path: '/tasks'
      fullPath: '/returns/$id/tasks'
      preLoaderRoute: typeof ReturnsIdTasksRouteImport
      parentRoute: typeof ReturnsIdRoute
    }
  }
}

interface FirmRouteChildren {
  FirmBillingRoute: typeof FirmBillingRoute
  FirmSettingsRoute: typeof FirmSettingsRoute
  FirmStaffRoute: typeof FirmStaffRoute
}

const FirmRouteChildren: FirmRouteChildren = {
  FirmBillingRoute: FirmBillingRoute,
  FirmSettingsRoute: FirmSettingsRoute,
  FirmStaffRoute: FirmStaffRoute,
}

const FirmRouteWithChildren = FirmRoute._addFileChildren(FirmRouteChildren)

interface ReturnRouteChildren {
  ReturnSignRoute: typeof ReturnSignRoute
}

const ReturnRouteChildren: ReturnRouteChildren = {
  ReturnSignRoute: ReturnSignRoute,
}

const ReturnRouteWithChildren =
  ReturnRoute._addFileChildren(ReturnRouteChildren)

interface ReturnsIdRouteChildren {
  ReturnsIdDocumentsRoute: typeof ReturnsIdDocumentsRoute
  ReturnsIdMessagesRoute: typeof ReturnsIdMessagesRoute
  ReturnsIdReviewRoute: typeof ReturnsIdReviewRoute
  ReturnsIdTasksRoute: typeof ReturnsIdTasksRoute
  ReturnsIdIndexRoute: typeof ReturnsIdIndexRoute
}

const ReturnsIdRouteChildren: ReturnsIdRouteChildren = {
  ReturnsIdDocumentsRoute: ReturnsIdDocumentsRoute,
  ReturnsIdMessagesRoute: ReturnsIdMessagesRoute,
  ReturnsIdReviewRoute: ReturnsIdReviewRoute,
  ReturnsIdTasksRoute: ReturnsIdTasksRoute,
  ReturnsIdIndexRoute: ReturnsIdIndexRoute,
}

const ReturnsIdRouteWithChildren = ReturnsIdRoute._addFileChildren(
  ReturnsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  DocumentsRoute: DocumentsRoute,
  FirmRoute: FirmRouteWithChildren,
  InboxRoute: InboxRoute,
  ProfileRoute: ProfileRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  ReturnRoute: ReturnRouteWithChildren,
  TasksRoute: TasksRoute,
  DesignBusinessOwnerRoute: DesignBusinessOwnerRoute,
  DesignReviewerRoute: DesignReviewerRoute,
  DesignSeasonalStaffRoute: DesignSeasonalStaffRoute,
  ReturnsIdRoute: ReturnsIdRouteWithChildren,
  ReturnsIndexRoute: ReturnsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
